### ISSUE TITLE
Loadmap loads faulty maps into memory

### ISSUE THREAD

**Issue by derekherbert** [derekherbert/Warzone#189]
- I created a non-connected map "non-connected.map" (currently in my PR)
- The console displays an error message, but the map is actually loaded into memory and you can proceed to assigncountries and start playing with the faulty map

- We may need to perform validateMap() at the beginning of assignCountries(). We probably need it when using the "next" command as well

**Comment by fzuray** [comment]
before assigning country, make sure the map is valid

**Comment by fzuray** [comment]
done
