### ISSUE TITLE
command "advance Sicily Sardinia"mistake

### ISSUE THREAD

**Issue by elliansjm** [derekherbert/Warzone#191]
The current force of the own country Sicily is 5, and the current force of the enemy country Sardinia is 0, but you can enter the command "advance Sicily Sardinia 4" twice. After executing the order, Sardinia is conquered and Sardinia has a force of 5.

**Comment by elliansjm** [comment]
18 Sardinia
                                      20 Majorca
                         13 Hungary                   p2          0
                                      12 Slovakia
                                      14 Austria
                         14 Austria                   p2          0
                                      16 Italy
                                       9 Germany
                                      11 Czech_Rep
                                      12 Slovakia
                                      13 Hungary
                                      15 Switzerland
                         15 Switzerland               p2          0
                                      16 Italy
                                      21 France
                                       9 Germany
                                      14 Austria
4 West_Europe[3]
                         20 Majorca                   p2          0
                                      18 Sardinia
                                      19 Corsica
                                      22 Spain
                         21 France                    p2          0
                                       1 England
                                      22 Spain
                                       6 Belgum
                                      24 Luxembourg
                                      15 Switzerland
                         22 Spain                     p1          0
                                       4 Rep_Ireland
                                      20 Majorca
                                      21 France
                                      23 Portugal
                         23 Portugal                  p2          0
                                      22 Spain
                         24 Luxembourg                p1          0
                                      21 France
                                       6 Belgum
                                       9 Germany
---------- Start to execute round [2] of orders
Success : Success to execute order:Deploy Order, issued by player [p1], deploying [4] armies to [Wales]
************************************************************************
** Continent[Bonus Army]  -  Country  -  neighbors -  Player  -  Armies       **
************************************************************************
1 North_Europe[5]
                          1 England                   p2          4
                                       2 Scotland
                                       3 N_Ireland
                                       4 Rep_Ireland
                                      21 France
                                       5 Wales
                                       6 Belgum
                                       7 Netherlands
                                       8 Denmark
                          2 Scotland                  p2          0
                                       1 England
                                       3 N_Ireland
                                       8 Denmark
                          3 N_Ireland                 p2          0
                                       1 England
                                       2 Scotland
                          4 Rep_Ireland               p1          0
                                       1 England
                                       5 Wales
                                      22 Spain
                          5 Wales                     p1          4
                                       1 England
                                       4 Rep_Ireland
                          6 Belgum                    p1          0
                                       1 England
                                      21 France
                                       7 Netherlands
                                      24 Luxembourg
                                       9 Germany
                          7 Netherlands               p2          0
                                       1 England
                                       6 Belgum
                                       9 Germany
2 East_Europe[4]
                          8 Denmark                   p1          0
                                       1 England
                                       2 Scotland
                                       9 Germany
                                      10 Poland
                          9 Germany                   p1          0
                                       6 Belgum
                                       7 Netherlands
                                       8 Denmark
                                      24 Luxembourg
                                      10 Poland
                                      11 Czech_Rep
                                      14 Austria
                                      15 Switzerland
                         10 Poland                    p1          0
                                       8 Denmark
                                       9 Germany
                                      11 Czech_Rep
                                      12 Slovakia
                         11 Czech_Rep                 p1          0
                                       9 Germany
                                      10 Poland
                                      12 Slovakia
                                      14 Austria
                         12 Slovakia                  p1          0
                                      10 Poland
                                      11 Czech_Rep
                                      13 Hungary
                                      14 Austria
3 South_Europe[5]
                         16 Italy                     p1          4
                                      17 Sicily
                                      18 Sardinia
                                      14 Austria
                                      15 Switzerland
                         17 Sicily                    p2          0
                                      16 Italy
                                      18 Sardinia
                         18 Sardinia                  p1          0
                                      16 Italy
                                      17 Sicily
                                      19 Corsica
                                      20 Majorca
                         19 Corsica                   p2          0
                                      18 Sardinia
                                      20 Majorca
                         13 Hungary                   p2          0
                                      12 Slovakia
                                      14 Austria
                         14 Austria                   p2          0
                                      16 Italy
                                       9 Germany
                                      11 Czech_Rep
                                      12 Slovakia
                                      13 Hungary
                                      15 Switzerland
                         15 Switzerland               p2          0
                                      16 Italy
                                      21 France
                                       9 Germany
                                      14 Austria
4 West_Europe[3]
                         20 Majorca                   p2          0
                                      18 Sardinia
                                      19 Corsica
                                      22 Spain
                         21 France                    p2          0
                                       1 England
                                      22 Spain
                                       6 Belgum
                                      24 Luxembourg
                                      15 Switzerland
                         22 Spain                     p1          0
                                       4 Rep_Ireland
                                      20 Majorca
                                      21 France
                                      23 Portugal
                         23 Portugal                  p2          0
                                      22 Spain
                         24 Luxembourg                p1          0
                                      21 France
                                       6 Belgum
                                       9 Germany
---------- Start to execute round [3] of orders
************************************************************************
** Continent[Bonus Army]  -  Country  -  neighbors -  Player  -  Armies       **
************************************************************************
1 North_Europe[5]
                          1 England                   p2          4
                                       2 Scotland
                                       3 N_Ireland
                                       4 Rep_Ireland
                                      21 France
                                       5 Wales
                                       6 Belgum
                                       7 Netherlands
                                       8 Denmark
                          2 Scotland                  p2          0
                                       1 England
                                       3 N_Ireland
                                       8 Denmark
                          3 N_Ireland                 p2          0
                                       1 England
                                       2 Scotland
                          4 Rep_Ireland               p1          0
                                       1 England
                                       5 Wales
                                      22 Spain
                          5 Wales                     p1          4
                                       1 England
                                       4 Rep_Ireland
                          6 Belgum                    p1          0
                                       1 England
                                      21 France
                                       7 Netherlands
                                      24 Luxembourg
                                       9 Germany
                          7 Netherlands               p2          0
                                       1 England
                                       6 Belgum
                                       9 Germany
2 East_Europe[4]
                          8 Denmark                   p1          0
                                       1 England
                                       2 Scotland
                                       9 Germany
                                      10 Poland
                          9 Germany                   p1          0
                                       6 Belgum
                                       7 Netherlands
                                       8 Denmark
                                      24 Luxembourg
                                      10 Poland
                                      11 Czech_Rep
                                      14 Austria
                                      15 Switzerland
                         10 Poland                    p1          0
                                       8 Denmark
                                       9 Germany
                                      11 Czech_Rep
                                      12 Slovakia
                         11 Czech_Rep                 p1          0
                                       9 Germany
                                      10 Poland
                                      12 Slovakia
                                      14 Austria
                         12 Slovakia                  p1          0
                                      10 Poland
                                      11 Czech_Rep
                                      13 Hungary
                                      14 Austria
3 South_Europe[5]
                         16 Italy                     p1          0
                                      17 Sicily
                                      18 Sardinia
                                      14 Austria
                                      15 Switzerland
                         17 Sicily                    p2          0
                                      16 Italy
                                      18 Sardinia
                         18 Sardinia                  p1          0
                                      16 Italy
                                      17 Sicily
                                      19 Corsica
                                      20 Majorca
                         19 Corsica                   p2          0
                                      18 Sardinia
                                      20 Majorca
                         13 Hungary                   p2          0
                                      12 Slovakia
                                      14 Austria
                         14 Austria                   p1          4
                                      16 Italy
                                       9 Germany
                                      11 Czech_Rep
                                      12 Slovakia
                                      13 Hungary
                                      15 Switzerland
                         15 Switzerland               p2          0
                                      16 Italy
                                      21 France
                                       9 Germany
                                      14 Austria
4 West_Europe[3]
                         20 Majorca                   p2          0
                                      18 Sardinia
                                      19 Corsica
                                      22 Spain
                         21 France                    p2          0
                                       1 England
                                      22 Spain
                                       6 Belgum
                                      24 Luxembourg
                                      15 Switzerland
                         22 Spain                     p1          0
                                       4 Rep_Ireland
                                      20 Majorca
                                      21 France
                                      23 Portugal
                         23 Portugal                  p2          0
                                      22 Spain
                         24 Luxembourg                p1          0
                                      21 France
                                       6 Belgum
                                       9 Germany
---------- Start to execute round [4] of orders
Success : Success to execute order:Advance Order, issued by player [p1], sending [-1] armies from  [Italy] to [Sicily]
************************************************************************
** Continent[Bonus Army]  -  Country  -  neighbors -  Player  -  Armies       **
************************************************************************
1 North_Europe[5]
                          1 England                   p2          4
                                       2 Scotland
                                       3 N_Ireland
                                       4 Rep_Ireland
                                      21 France
                                       5 Wales
                                       6 Belgum
                                       7 Netherlands
                                       8 Denmark
                          2 Scotland                  p2          0
                                       1 England
                                       3 N_Ireland
                                       8 Denmark
                          3 N_Ireland                 p2          0
                                       1 England
                                       2 Scotland
                          4 Rep_Ireland               p1          0
                                       1 England
                                       5 Wales
                                      22 Spain
                          5 Wales                     p1          4
                                       1 England
                                       4 Rep_Ireland
                          6 Belgum                    p1          0
                                       1 England
                                      21 France
                                       7 Netherlands
                                      24 Luxembourg
                                       9 Germany
                          7 Netherlands               p2          0
                                       1 England
                                       6 Belgum
                                       9 Germany
2 East_Europe[4]
                          8 Denmark                   p1          0
                                       1 England
                                       2 Scotland
                                       9 Germany
                                      10 Poland
                          9 Germany                   p1          0
                                       6 Belgum
                                       7 Netherlands
                                       8 Denmark
                                      24 Luxembourg
                                      10 Poland
                                      11 Czech_Rep
                                      14 Austria
                                      15 Switzerland
                         10 Poland                    p1          0
                                       8 Denmark
                                       9 Germany
                                      11 Czech_Rep
                                      12 Slovakia
                         11 Czech_Rep                 p1          0
                                       9 Germany
                                      10 Poland
                                      12 Slovakia
                                      14 Austria
                         12 Slovakia                  p1          0
                                      10 Poland
                                      11 Czech_Rep
                                      13 Hungary
                                      14 Austria
3 South_Europe[5]
                         16 Italy                     p1          -1
                                      17 Sicily
                                      18 Sardinia
                                      14 Austria
                                      15 Switzerland
                         17 Sicily                    p2          0
                                      16 Italy
                                      18 Sardinia
                         18 Sardinia                  p1          0
                                      16 Italy
                                      17 Sicily
                                      19 Corsica
                                      20 Majorca
                         19 Corsica                   p2          0
                                      18 Sardinia
                                      20 Majorca
                         13 Hungary                   p2          0
                                      12 Slovakia
                                      14 Austria
                         14 Austria                   p1          4
                                      16 Italy
                                       9 Germany
                                      11 Czech_Rep
                                      12 Slovakia
                                      13 Hungary
                                      15 Switzerland
                         15 Switzerland               p2          0
                                      16 Italy
                                      21 France
                                       9 Germany
                                      14 Austria
4 West_Europe[3]
                         20 Majorca                   p2          0
                                      18 Sardinia
                                      19 Corsica
                                      22 Spain
                         21 France                    p2          0
                                       1 England
                                      22 Spain
                                       6 Belgum
                                      24 Luxembourg
                                      15 Switzerland
                         22 Spain                     p1          0
                                       4 Rep_Ireland
                                      20 Majorca
                                      21 France
                                      23 Portugal
                         23 Portugal                  p2          0
                                      22 Spain
                         24 Luxembourg                p1          0
                                      21 France
                                       6 Belgum
                                       9 Germany
-------------------- Finish executing orders for this turn
p1 was assigned a BOMB card.

[Status] Game Phase:OrderExecution | Demo Mode:false | Debug Mode:false | Player:2 | Continent:4 | Country:24
Please input the command, type [help] for help, type [quit] to quit the game.
help
*****************************************    HELP IN PHASE [ OrderExecution ]  *********************************
Commands available for current game phase: OrderExecution
 You are in game ORDER_EXECUTION phase, you can issue orders. 
 -  next   [will go to next phase]
 -  play   [start to execute order]
 -  showmap 

*****************************************    HELP IN PHASE [ OrderExecution ]  *********************************

[Status] Game Phase:OrderExecution | Demo Mode:false | Debug Mode:false | Player:2 | Continent:4 | Country:24
Please input the command, type [help] for help, type [quit] to quit the game.
next
-------------------- Start to assign reinforcements
---------- Start to assign reinforcements for player [p1]
---------- Start to assign reinforcements for player [p2]
-------------------- Finish assigning reinforcements
new phase: Reinforcement

[Status] Game Phase:Reinforcement | Demo Mode:false | Debug Mode:false | Player:2 | Continent:4 | Country:24
Please input the command, type [help] for help, type [quit] to quit the game.
play
Invalid command in state Reinforcement

[Status] Game Phase:Reinforcement | Demo Mode:false | Debug Mode:false | Player:2 | Continent:4 | Country:24
Please input the command, type [help] for help, type [quit] to quit the game.
help
*****************************************    HELP IN PHASE [ Reinforcement ]  *********************************
Commands available for current game phase: Reinforcement
 -  next
 -  showmap
 -  reboot 

*****************************************    HELP IN PHASE [ Reinforcement ]  *********************************

[Status] Game Phase:Reinforcement | Demo Mode:false | Debug Mode:false | Player:2 | Continent:4 | Country:24
Please input the command, type [help] for help, type [quit] to quit the game.
next
new phase: IssueOrder

[Status] Game Phase:IssueOrder | Demo Mode:false | Debug Mode:false | Player:2 | Continent:4 | Country:24
Please input the command, type [help] for help, type [quit] to quit the game.
help
*****************************************    HELP IN PHASE [ IssueOrder ]  *********************************
Commands available for current game phase: IssueOrder
 You are in game ISSUR_ORDER phase, you can issue orders. 
 -  play   [start to issue order]
 -  deploy countryID num
 -  advance countrynamefrom countynameto numarmies
 -  bomb countryID
 -  blockade countryID
 -  airlift sourcecountryID targetcountryID numarmies
 -  negotiate playerID
 -  showmap 
 -  done   [finish order]

*****************************************    HELP IN PHASE [ IssueOrder ]  *********************************

[Status] Game Phase:IssueOrder | Demo Mode:false | Debug Mode:false | Player:2 | Continent:4 | Country:24
Please input the command, type [help] for help, type [quit] to quit the game.
play
-------------------- Start to issue orders
---------- Start to issue orders for player [p1]
----- Player [p1] has [13] Countries 
Country ID : [4] , Name : [Rep_Ireland]
Country ID : [5] , Name : [Wales]
Country ID : [6] , Name : [Belgum]
Country ID : [8] , Name : [Denmark]
Country ID : [9] , Name : [Germany]
Country ID : [10] , Name : [Poland]
Country ID : [11] , Name : [Czech_Rep]
Country ID : [12] , Name : [Slovakia]
Country ID : [14] , Name : [Austria]
Country ID : [16] , Name : [Italy]
Country ID : [18] , Name : [Sardinia]
Country ID : [22] , Name : [Spain]
Country ID : [24] , Name : [Luxembourg]
----- Player [p1] has [1] cards available:
BOMB
----- Player [p1] has issued [0] orders:
Please input command for player [p1] , there is [8] army available for deployment
deploy 24 3
Deploy Order, issued by player [p1], deploying [3] armies to [Luxembourg]
---------- Start to issue orders for player [p2]
----- Player [p2] has [11] Countries 
Country ID : [1] , Name : [England]
Country ID : [17] , Name : [Sicily]
Country ID : [2] , Name : [Scotland]
Country ID : [19] , Name : [Corsica]
Country ID : [3] , Name : [N_Ireland]
Country ID : [20] , Name : [Majorca]
Country ID : [21] , Name : [France]
Country ID : [7] , Name : [Netherlands]
Country ID : [23] , Name : [Portugal]
Country ID : [13] , Name : [Hungary]
Country ID : [15] , Name : [Switzerland]
----- Player [p2] has [0] cards available:
----- Player [p2] has issued [0] orders:
Please input command for player [p2] , there is [3] army available for deployment
deploy 17 1
Deploy Order, issued by player [p2], deploying [1] armies to [Sicily]
---------- Start to issue orders for player [p1]
----- Player [p1] has [13] Countries 
Country ID : [4] , Name : [Rep_Ireland]
Country ID : [5] , Name : [Wales]
Country ID : [6] , Name : [Belgum]
Country ID : [8] , Name : [Denmark]
Country ID : [9] , Name : [Germany]
Country ID : [10] , Name : [Poland]
Country ID : [11] , Name : [Czech_Rep]
Country ID : [12] , Name : [Slovakia]
Country ID : [14] , Name : [Austria]
Country ID : [16] , Name : [Italy]
Country ID : [18] , Name : [Sardinia]
Country ID : [22] , Name : [Spain]
Country ID : [24] , Name : [Luxembourg]
----- Player [p1] has [1] cards available:
BOMB
----- Player [p1] has issued [1] orders:
Deploy Order, issued by player [p1], deploying [3] armies to [Luxembourg]
Please input command for player [p1] , there is [5] army available for deployment
done
---------- Finish issuing order for player [p1] in this turn.
---------- Start to issue orders for player [p2]
----- Player [p2] has [11] Countries 
Country ID : [1] , Name : [England]
Country ID : [17] , Name : [Sicily]
Country ID : [2] , Name : [Scotland]
Country ID : [19] , Name : [Corsica]
Country ID : [3] , Name : [N_Ireland]
Country ID : [20] , Name : [Majorca]
Country ID : [21] , Name : [France]
Country ID : [7] , Name : [Netherlands]
Country ID : [23] , Name : [Portugal]
Country ID : [13] , Name : [Hungary]
Country ID : [15] , Name : [Switzerland]
----- Player [p2] has [0] cards available:
----- Player [p2] has issued [1] orders:
Deploy Order, issued by player [p2], deploying [1] armies to [Sicily]
Please input command for player [p2] , there is [2] army available for deployment
done
---------- Finish issuing order for player [p2] in this turn.
-------------------- Finish issuing orders for this turn
new phase: OrderExecution

[Status] Game Phase:OrderExecution | Demo Mode:false | Debug Mode:false | Player:2 | Continent:4 | Country:24
Please input the command, type [help] for help, type [quit] to quit the game.
play
-------------------- Start to execute orders.
---------- Start to execute round [1] of orders
Success : Success to execute order:Deploy Order, issued by player [p1], deploying [3] armies to [Luxembourg]
************************************************************************
** Continent[Bonus Army]  -  Country  -  neighbors -  Player  -  Armies       **
************************************************************************
1 North_Europe[5]
                          1 England                   p2          4
                                       2 Scotland
                                       3 N_Ireland
                                       4 Rep_Ireland
                                      21 France
                                       5 Wales
                                       6 Belgum
                                       7 Netherlands
                                       8 Denmark
                          2 Scotland                  p2          0
                                       1 England
                                       3 N_Ireland
                                       8 Denmark
                          3 N_Ireland                 p2          0
                                       1 England
                                       2 Scotland
                          4 Rep_Ireland               p1          0
                                       1 England
                                       5 Wales
                                      22 Spain
                          5 Wales                     p1          4
                                       1 England
                                       4 Rep_Ireland
                          6 Belgum                    p1          0
                                       1 England
                                      21 France
                                       7 Netherlands
                                      24 Luxembourg
                                       9 Germany
                          7 Netherlands               p2          0
                                       1 England
                                       6 Belgum
                                       9 Germany
2 East_Europe[4]
                          8 Denmark                   p1          0
                                       1 England
                                       2 Scotland
                                       9 Germany
                                      10 Poland
                          9 Germany                   p1          0
                                       6 Belgum
                                       7 Netherlands
                                       8 Denmark
                                      24 Luxembourg
                                      10 Poland
                                      11 Czech_Rep
                                      14 Austria
                                      15 Switzerland
                         10 Poland                    p1          0
                                       8 Denmark
                                       9 Germany
                                      11 Czech_Rep
                                      12 Slovakia
                         11 Czech_Rep                 p1          0
                                       9 Germany
                                      10 Poland
                                      12 Slovakia
                                      14 Austria
                         12 Slovakia                  p1          0
                                      10 Poland
                                      11 Czech_Rep
                                      13 Hungary
                                      14 Austria
3 South_Europe[5]
                         16 Italy                     p1          -1
                                      17 Sicily
                                      18 Sardinia
                                      14 Austria
                                      15 Switzerland
                         17 Sicily                    p2          0
                                      16 Italy
                                      18 Sardinia
                         18 Sardinia                  p1          0
                                      16 Italy
                                      17 Sicily
                                      19 Corsica
                                      20 Majorca
                         19 Corsica                   p2          0
                                      18 Sardinia
                                      20 Majorca
                         13 Hungary                   p2          0
                                      12 Slovakia
                                      14 Austria
                         14 Austria                   p1          4
                                      16 Italy
                                       9 Germany
                                      11 Czech_Rep
                                      12 Slovakia
                                      13 Hungary
                                      15 Switzerland
                         15 Switzerland               p2          0
                                      16 Italy
                                      21 France
                                       9 Germany
                                      14 Austria
4 West_Europe[3]
                         20 Majorca                   p2          0
                                      18 Sardinia
                                      19 Corsica
                                      22 Spain
                         21 France                    p2          0
                                       1 England
                                      22 Spain
                                       6 Belgum
                                      24 Luxembourg
                                      15 Switzerland
                         22 Spain                     p1          0
                                       4 Rep_Ireland
                                      20 Majorca
                                      21 France
                                      23 Portugal
                         23 Portugal                  p2          0
                                      22 Spain
                         24 Luxembourg                p1          3
                                      21 France
                                       6 Belgum
                                       9 Germany
Success : Success to execute order:Deploy Order, issued by player [p2], deploying [1] armies to [Sicily]
************************************************************************
** Continent[Bonus Army]  -  Country  -  neighbors -  Player  -  Armies       **
************************************************************************
1 North_Europe[5]
                          1 England                   p2          4
                                       2 Scotland
                                       3 N_Ireland
                                       4 Rep_Ireland
                                      21 France
                                       5 Wales
                                       6 Belgum
                                       7 Netherlands
                                       8 Denmark
                          2 Scotland                  p2          0
                                       1 England
                                       3 N_Ireland
                                       8 Denmark
                          3 N_Ireland                 p2          0
                                       1 England
                                       2 Scotland
                          4 Rep_Ireland               p1          0
                                       1 England
                                       5 Wales
                                      22 Spain
                          5 Wales                     p1          4
                                       1 England
                                       4 Rep_Ireland
                          6 Belgum                    p1          0
                                       1 England
                                      21 France
                                       7 Netherlands
                                      24 Luxembourg
                                       9 Germany
                          7 Netherlands               p2          0
                                       1 England
                                       6 Belgum
                                       9 Germany
2 East_Europe[4]
                          8 Denmark                   p1          0
                                       1 England
                                       2 Scotland
                                       9 Germany
                                      10 Poland
                          9 Germany                   p1          0
                                       6 Belgum
                                       7 Netherlands
                                       8 Denmark
                                      24 Luxembourg
                                      10 Poland
                                      11 Czech_Rep
                                      14 Austria
                                      15 Switzerland
                         10 Poland                    p1          0
                                       8 Denmark
                                       9 Germany
                                      11 Czech_Rep
                                      12 Slovakia
                         11 Czech_Rep                 p1          0
                                       9 Germany
                                      10 Poland
                                      12 Slovakia
                                      14 Austria
                         12 Slovakia                  p1          0
                                      10 Poland
                                      11 Czech_Rep
                                      13 Hungary
                                      14 Austria
3 South_Europe[5]
                         16 Italy                     p1          -1
                                      17 Sicily
                                      18 Sardinia
                                      14 Austria
                                      15 Switzerland
                         17 Sicily                    p2          1
                                      16 Italy
                                      18 Sardinia
                         18 Sardinia                  p1          0
                                      16 Italy
                                      17 Sicily
                                      19 Corsica
                                      20 Majorca
                         19 Corsica                   p2          0
                                      18 Sardinia
                                      20 Majorca
                         13 Hungary                   p2          0
                                      12 Slovakia
                                      14 Austria
                         14 Austria                   p1          4
                                      16 Italy
                                       9 Germany
                                      11 Czech_Rep
                                      12 Slovakia
                                      13 Hungary
                                      15 Switzerland
                         15 Switzerland               p2          0
                                      16 Italy
                                      21 France
                                       9 Germany
                                      14 Austria
4 West_Europe[3]
                         20 Majorca                   p2          0
                                      18 Sardinia
                                      19 Corsica
                                      22 Spain
                         21 France                    p2          0
                                       1 England
                                      22 Spain
                                       6 Belgum
                                      24 Luxembourg
                                      15 Switzerland
                         22 Spain                     p1          0
                                       4 Rep_Ireland
                                      20 Majorca
                                      21 France
                                      23 Portugal
                         23 Portugal                  p2          0
                                      22 Spain
                         24 Luxembourg                p1          3
                                      21 France
                                       6 Belgum
                                       9 Germany
-------------------- Finish executing orders for this turn

[Status] Game Phase:OrderExecution | Demo Mode:false | Debug Mode:false | Player:2 | Continent:4 | Country:24
Please input the command, type [help] for help, type [quit] to quit the game.
next
-------------------- Start to assign reinforcements
---------- Start to assign reinforcements for player [p1]
---------- Start to assign reinforcements for player [p2]
-------------------- Finish assigning reinforcements
new phase: Reinforcement

[Status] Game Phase:Reinforcement | Demo Mode:false | Debug Mode:false | Player:2 | Continent:4 | Country:24
Please input the command, type [help] for help, type [quit] to quit the game.
next
new phase: IssueOrder

[Status] Game Phase:IssueOrder | Demo Mode:false | Debug Mode:false | Player:2 | Continent:4 | Country:24
Please input the command, type [help] for help, type [quit] to quit the game.
play
-------------------- Start to issue orders
---------- Start to issue orders for player [p1]
----- Player [p1] has [13] Countries 
Country ID : [4] , Name : [Rep_Ireland]
Country ID : [5] , Name : [Wales]
Country ID : [6] , Name : [Belgum]
Country ID : [8] , Name : [Denmark]
Country ID : [9] , Name : [Germany]
Country ID : [10] , Name : [Poland]
Country ID : [11] , Name : [Czech_Rep]
Country ID : [12] , Name : [Slovakia]
Country ID : [14] , Name : [Austria]
Country ID : [16] , Name : [Italy]
Country ID : [18] , Name : [Sardinia]
Country ID : [22] , Name : [Spain]
Country ID : [24] , Name : [Luxembourg]
----- Player [p1] has [1] cards available:
BOMB
----- Player [p1] has issued [0] orders:
Please input command for player [p1] , there is [8] army available for deployment
done
---------- Finish issuing order for player [p1] in this turn.
---------- Start to issue orders for player [p2]
----- Player [p2] has [11] Countries 
Country ID : [1] , Name : [England]
Country ID : [17] , Name : [Sicily]
Country ID : [2] , Name : [Scotland]
Country ID : [19] , Name : [Corsica]
Country ID : [3] , Name : [N_Ireland]
Country ID : [20] , Name : [Majorca]
Country ID : [21] , Name : [France]
Country ID : [7] , Name : [Netherlands]
Country ID : [23] , Name : [Portugal]
Country ID : [13] , Name : [Hungary]
Country ID : [15] , Name : [Switzerland]
----- Player [p2] has [0] cards available:
----- Player [p2] has issued [0] orders:
Please input command for player [p2] , there is [3] army available for deployment
done
---------- Finish issuing order for player [p2] in this turn.
-------------------- Finish issuing orders for this turn
new phase: OrderExecution

[Status] Game Phase:OrderExecution | Demo Mode:false | Debug Mode:false | Player:2 | Continent:4 | Country:24
Please input the command, type [help] for help, type [quit] to quit the game.
play
-------------------- Start to execute orders.
-------------------- Finish executing orders for this turn

[Status] Game Phase:OrderExecution | Demo Mode:false | Debug Mode:false | Player:2 | Continent:4 | Country:24
Please input the command, type [help] for help, type [quit] to quit the game.
next
-------------------- Start to assign reinforcements
---------- Start to assign reinforcements for player [p1]
---------- Start to assign reinforcements for player [p2]
-------------------- Finish assigning reinforcements
new phase: Reinforcement

[Status] Game Phase:Reinforcement | Demo Mode:false | Debug Mode:false | Player:2 | Continent:4 | Country:24
Please input the command, type [help] for help, type [quit] to quit the game.
play
Invalid command in state Reinforcement

[Status] Game Phase:Reinforcement | Demo Mode:false | Debug Mode:false | Player:2 | Continent:4 | Country:24
Please input the command, type [help] for help, type [quit] to quit the game.
help
*****************************************    HELP IN PHASE [ Reinforcement ]  *********************************
Commands available for current game phase: Reinforcement
 -  next
 -  showmap
 -  reboot 

*****************************************    HELP IN PHASE [ Reinforcement ]  *********************************

[Status] Game Phase:Reinforcement | Demo Mode:false | Debug Mode:false | Player:2 | Continent:4 | Country:24
Please input the command, type [help] for help, type [quit] to quit the game.
next
new phase: IssueOrder

[Status] Game Phase:IssueOrder | Demo Mode:false | Debug Mode:false | Player:2 | Continent:4 | Country:24
Please input the command, type [help] for help, type [quit] to quit the game.
play
-------------------- Start to issue orders
---------- Start to issue orders for player [p1]
----- Player [p1] has [13] Countries 
Country ID : [4] , Name : [Rep_Ireland]
Country ID : [5] , Name : [Wales]
Country ID : [6] , Name : [Belgum]
Country ID : [8] , Name : [Denmark]
Country ID : [9] , Name : [Germany]
Country ID : [10] , Name : [Poland]
Country ID : [11] , Name : [Czech_Rep]
Country ID : [12] , Name : [Slovakia]
Country ID : [14] , Name : [Austria]
Country ID : [16] , Name : [Italy]
Country ID : [18] , Name : [Sardinia]
Country ID : [22] , Name : [Spain]
Country ID : [24] , Name : [Luxembourg]
----- Player [p1] has [1] cards available:
BOMB
----- Player [p1] has issued [0] orders:
Please input command for player [p1] , there is [8] army available for deployment
help
*****************************************    HELP IN PHASE [ IssueOrder ]  *********************************
Commands available for current game phase: IssueOrder
 You are in game ISSUR_ORDER phase, you can issue orders. 
 -  play   [start to issue order]
 -  deploy countryID num
 -  advance countrynamefrom countynameto numarmies
 -  bomb countryID
 -  blockade countryID
 -  airlift sourcecountryID targetcountryID numarmies
 -  negotiate playerID
 -  showmap 
 -  done   [finish order]

*****************************************    HELP IN PHASE [ IssueOrder ]  *********************************
----- Player [p1] has [13] Countries 
Country ID : [4] , Name : [Rep_Ireland]
Country ID : [5] , Name : [Wales]
Country ID : [6] , Name : [Belgum]
Country ID : [8] , Name : [Denmark]
Country ID : [9] , Name : [Germany]
Country ID : [10] , Name : [Poland]
Country ID : [11] , Name : [Czech_Rep]
Country ID : [12] , Name : [Slovakia]
Country ID : [14] , Name : [Austria]
Country ID : [16] , Name : [Italy]
Country ID : [18] , Name : [Sardinia]
Country ID : [22] , Name : [Spain]
Country ID : [24] , Name : [Luxembourg]
----- Player [p1] has [1] cards available:
BOMB
----- Player [p1] has issued [0] orders:
Please input command for player [p1] , there is [8] army available for deployment
bomb 2
Bomb Order, issued by player [p1], bombing [Scotland]
---------- Start to issue orders for player [p2]
----- Player [p2] has [11] Countries 
Country ID : [1] , Name : [England]
Country ID : [17] , Name : [Sicily]
Country ID : [2] , Name : [Scotland]
Country ID : [19] , Name : [Corsica]
Country ID : [3] , Name : [N_Ireland]
Country ID : [20] , Name : [Majorca]
Country ID : [21] , Name : [France]
Country ID : [7] , Name : [Netherlands]
Country ID : [23] , Name : [Portugal]
Country ID : [13] , Name : [Hungary]
Country ID : [15] , Name : [Switzerland]
----- Player [p2] has [0] cards available:
----- Player [p2] has issued [0] orders:
Please input command for player [p2] , there is [3] army available for deployment
deploy 15 3
Deploy Order, issued by player [p2], deploying [3] armies to [Switzerland]
---------- Start to issue orders for player [p1]
----- Player [p1] has [13] Countries 
Country ID : [4] , Name : [Rep_Ireland]
Country ID : [5] , Name : [Wales]
Country ID : [6] , Name : [Belgum]
Country ID : [8] , Name : [Denmark]
Country ID : [9] , Name : [Germany]
Country ID : [10] , Name : [Poland]
Country ID : [11] , Name : [Czech_Rep]
Country ID : [12] , Name : [Slovakia]
Country ID : [14] , Name : [Austria]
Country ID : [16] , Name : [Italy]
Country ID : [18] , Name : [Sardinia]
Country ID : [22] , Name : [Spain]
Country ID : [24] , Name : [Luxembourg]
----- Player [p1] has [0] cards available:
----- Player [p1] has issued [1] orders:
Bomb Order, issued by player [p1], bombing [Scotland]
Please input command for player [p1] , there is [8] army available for deployment
showmap
************************************************************************
** Continent[Bonus Army]  -  Country  -  neighbors -  Player  -  Armies       **
************************************************************************
1 North_Europe[5]
                          1 England                   p2          4
                                       2 Scotland
                                       3 N_Ireland
                                       4 Rep_Ireland
                                      21 France
                                       5 Wales
                                       6 Belgum
                                       7 Netherlands
                                       8 Denmark
                          2 Scotland                  p2          0
                                       1 England
                                       3 N_Ireland
                                       8 Denmark
                          3 N_Ireland                 p2          0
                                       1 England
                                       2 Scotland
                          4 Rep_Ireland               p1          0
                                       1 England
                                       5 Wales
                                      22 Spain
                          5 Wales                     p1          4
                                       1 England
                                       4 Rep_Ireland
                          6 Belgum                    p1          0
                                       1 England
                                      21 France
                                       7 Netherlands
                                      24 Luxembourg
                                       9 Germany
                          7 Netherlands               p2          0
                                       1 England
                                       6 Belgum
                                       9 Germany
2 East_Europe[4]
                          8 Denmark                   p1          0
                                       1 England
                                       2 Scotland
                                       9 Germany
                                      10 Poland
                          9 Germany                   p1          0
                                       6 Belgum
                                       7 Netherlands
                                       8 Denmark
                                      24 Luxembourg
                                      10 Poland
                                      11 Czech_Rep
                                      14 Austria
                                      15 Switzerland
                         10 Poland                    p1          0
                                       8 Denmark
                                       9 Germany
                                      11 Czech_Rep
                                      12 Slovakia
                         11 Czech_Rep                 p1          0
                                       9 Germany
                                      10 Poland
                                      12 Slovakia
                                      14 Austria
                         12 Slovakia                  p1          0
                                      10 Poland
                                      11 Czech_Rep
                                      13 Hungary
                                      14 Austria
3 South_Europe[5]
                         16 Italy                     p1          -1
                                      17 Sicily
                                      18 Sardinia
                                      14 Austria
                                      15 Switzerland
                         17 Sicily                    p2          1
                                      16 Italy
                                      18 Sardinia
                         18 Sardinia                  p1          0
                                      16 Italy
                                      17 Sicily
                                      19 Corsica
                                      20 Majorca
                         19 Corsica                   p2          0
                                      18 Sardinia
                                      20 Majorca
                         13 Hungary                   p2          0
                                      12 Slovakia
                                      14 Austria
                         14 Austria                   p1          4
                                      16 Italy
                                       9 Germany
                                      11 Czech_Rep
                                      12 Slovakia
                                      13 Hungary
                                      15 Switzerland
                         15 Switzerland               p2          0
                                      16 Italy
                                      21 France
                                       9 Germany
                                      14 Austria
4 West_Europe[3]

**Comment by amyhcy** [comment]
fixed
